import type z from "zod";
import type { gitHubNodeSchema, gmailNodeSchema, notionNodeSchema } from "@/schemas/index.js";
import type { aiNodeSchema } from "@/schemas/nodes/integrations/ai.schema.js";
import type { calcomNodeSchema } from "@/schemas/nodes/integrations/calcom.schema.js";
import type { discordNodeSchema } from "@/schemas/nodes/integrations/discord.schema.js";
import type { googleCalendarNodeSchema } from "@/schemas/nodes/integrations/google-calendar.schema.js";
import type { googleDriveNodeSchema } from "@/schemas/nodes/integrations/google-drive.schema.js";
import type { googleSheetsNodeSchema } from "@/schemas/nodes/integrations/google-sheets.schema.js";
import type { jiraNodeSchema } from "@/schemas/nodes/integrations/jira.schema.js";
import type { linearNodeSchema } from "@/schemas/nodes/integrations/linear.schema.js";
import type { razorpayNodeSchema } from "@/schemas/nodes/integrations/razorpay.schema.js";
import type { slackNodeSchema } from "@/schemas/nodes/integrations/slack.schema.js";
import type { telegramNodeSchema } from "@/schemas/nodes/integrations/telegram.schema.js";

export type AiNode = z.infer<typeof aiNodeSchema>;
export type CalcomNode = z.infer<typeof calcomNodeSchema>;
export type GoogleDriveNode = z.infer<typeof googleDriveNodeSchema>;
export type GoogleCalendarNode = z.infer<typeof googleCalendarNodeSchema>;
export type GoogleSheetsNode = z.infer<typeof googleSheetsNodeSchema>;
export type GmailNode = z.infer<typeof gmailNodeSchema>;
export type GitHubNode = z.infer<typeof gitHubNodeSchema>;
export type DiscordNode = z.infer<typeof discordNodeSchema>;
export type JiraNode = z.infer<typeof jiraNodeSchema>;
export type LinearNode = z.infer<typeof linearNodeSchema>;
export type NotionNode = z.infer<typeof notionNodeSchema>;
export type RazorpayNode = z.infer<typeof razorpayNodeSchema>;
export type SlackNode = z.infer<typeof slackNodeSchema>;
export type TelegramNode = z.infer<typeof telegramNodeSchema>;
