import type z from "zod";
import type {
	gitHubNodeSchema,
	gmailNodeSchema,
	notionNodeSchema,
} from "@/schemas/index.js";
import type { aiNodeSchema } from "@/schemas/nodes/integrations/ai.schema.js";
import type { airtableNodeSchema } from "@/schemas/nodes/integrations/airtable.schema.js";
import type { asanaNodeSchema } from "@/schemas/nodes/integrations/asana.schema.js";
import type { calcomNodeSchema } from "@/schemas/nodes/integrations/calcom.schema.js";
import type { clickupNodeSchema } from "@/schemas/nodes/integrations/clickup.schema.js";
import type { discordNodeSchema } from "@/schemas/nodes/integrations/discord.schema.js";
import type { firebaseNodeSchema } from "@/schemas/nodes/integrations/firebase.schema.js";
import type { googleCalendarNodeSchema } from "@/schemas/nodes/integrations/google-calendar.schema.js";
import type { googleDocsNodeSchema } from "@/schemas/nodes/integrations/google-docs.schema.js";
import type { googleDriveNodeSchema } from "@/schemas/nodes/integrations/google-drive.schema.js";
import type { googleSheetsNodeSchema } from "@/schemas/nodes/integrations/google-sheets.schema.js";
import type { hubspotNodeSchema } from "@/schemas/nodes/integrations/hubspot.schema.js";
import type { jiraNodeSchema } from "@/schemas/nodes/integrations/jira.schema.js";
import type { linearNodeSchema } from "@/schemas/nodes/integrations/linear.schema.js";
import type { mailchimpNodeSchema } from "@/schemas/nodes/integrations/mailchimp.schema.js";
import type { mongodbNodeSchema } from "@/schemas/nodes/integrations/mongodb.schema.js";
import type { postgresNodeSchema } from "@/schemas/nodes/integrations/postgres.schema.js";
import type { razorpayNodeSchema } from "@/schemas/nodes/integrations/razorpay.schema.js";
import type { redisNodeSchema } from "@/schemas/nodes/integrations/redis.schema.js";
import type { sentryNodeSchema } from "@/schemas/nodes/integrations/sentry.schema.js";
import type { slackNodeSchema } from "@/schemas/nodes/integrations/slack.schema.js";
import type { supabaseNodeSchema } from "@/schemas/nodes/integrations/supabase.schema.js";
import type { telegramNodeSchema } from "@/schemas/nodes/integrations/telegram.schema.js";
import type { todoistNodeSchema } from "@/schemas/nodes/integrations/todoist.schema.js";
import type { trelloNodeSchema } from "@/schemas/nodes/integrations/trello.schema.js";
import type { twilioNodeSchema } from "@/schemas/nodes/integrations/twilio.schema.js";

export type AirtableNode = z.infer<typeof airtableNodeSchema>;
export type AiNode = z.infer<typeof aiNodeSchema>;
export type AsanaNode = z.infer<typeof asanaNodeSchema>;
export type CalcomNode = z.infer<typeof calcomNodeSchema>;
export type ClickUpNode = z.infer<typeof clickupNodeSchema>;
export type GoogleDriveNode = z.infer<typeof googleDriveNodeSchema>;
export type GoogleCalendarNode = z.infer<typeof googleCalendarNodeSchema>;
export type GoogleDocsNode = z.infer<typeof googleDocsNodeSchema>;
export type GoogleSheetsNode = z.infer<typeof googleSheetsNodeSchema>;
export type HubSpotNode = z.infer<typeof hubspotNodeSchema>;
export type GmailNode = z.infer<typeof gmailNodeSchema>;
export type GitHubNode = z.infer<typeof gitHubNodeSchema>;
export type DiscordNode = z.infer<typeof discordNodeSchema>;
export type FirebaseNode = z.infer<typeof firebaseNodeSchema>;
export type JiraNode = z.infer<typeof jiraNodeSchema>;
export type LinearNode = z.infer<typeof linearNodeSchema>;
export type MailchimpNode = z.infer<typeof mailchimpNodeSchema>;
export type MongodbNode = z.infer<typeof mongodbNodeSchema>;
export type PostgresNode = z.infer<typeof postgresNodeSchema>;
export type RedisNode = z.infer<typeof redisNodeSchema>;
export type NotionNode = z.infer<typeof notionNodeSchema>;
export type RazorpayNode = z.infer<typeof razorpayNodeSchema>;
export type SentryNode = z.infer<typeof sentryNodeSchema>;
export type SlackNode = z.infer<typeof slackNodeSchema>;
export type SupabaseNode = z.infer<typeof supabaseNodeSchema>;
export type TelegramNode = z.infer<typeof telegramNodeSchema>;
export type TodoistNode = z.infer<typeof todoistNodeSchema>;
export type TrelloNode = z.infer<typeof trelloNodeSchema>;
export type TwilioNode = z.infer<typeof twilioNodeSchema>;
